import React, { useState, useEffect, useRef } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useTheme } from '@/contexts/ThemeContext'
import { SEOHead } from '@/components/seo/SEOHead'
import { generateImageObjectSchema, generateBreadcrumbSchema } from '@/utils/seo'
import { Zap, Sparkles, Image, Download, Star, Wand2, Cpu, Palette, Search } from 'lucide-react'
import { EnhancedWallpaperCardAdapter } from '@/components/wallpapers/EnhancedWallpaperCardAdapter'

const aiCategories = [
  { name: 'AI Abstract', slug: 'ai-abstract', description: 'Futuristic abstract art generated by AI', icon: '🎨' },
  { name: 'AI Nature', slug: 'ai-nature', description: 'Stunning landscapes created by artificial intelligence', icon: '🌿' },
  { name: 'AI Space', slug: 'ai-space', description: 'Cosmic scenes and galaxies from AI imagination', icon: '🌌' },
  { name: 'AI Cyberpunk', slug: 'ai-cyberpunk', description: 'Neon-soaked futuristic cityscapes', icon: '🌃' },
  { name: 'AI Fantasy', slug: 'ai-fantasy', description: 'Magical worlds and creatures', icon: '🧙' },
  { name: 'AI Minimalist', slug: 'ai-minimalist', description: 'Clean, simple AI-generated designs', icon: '⚪' }
]

const aiFeatures = [
  {
    icon: <Cpu className="w-6 h-6" />,
    title: 'Advanced AI Models',
    description: 'Generated using state-of-the-art AI algorithms including Stable Diffusion and DALL-E'
  },
  {
    icon: <Palette className="w-6 h-6" />,
    title: 'Unique Artwork',
    description: 'Every wallpaper is one-of-a-kind, created by AI with no duplicates'
  },
  {
    icon: <Zap className="w-6 h-6" />,
    title: 'High Resolution',
    description: '4K and 8K quality AI-generated wallpapers optimized for all devices'
  },
  {
    icon: <Sparkles className="w-6 h-6" />,
    title: 'Daily Generation',
    description: 'New AI wallpapers created and added to our collection every day'
  }
]

export default function AIWallpapersPage() {
  const { theme } = useTheme()
  const [searchParams, setSearchParams] = useSearchParams()
  const [searchTerm, setSearchTerm] = useState(searchParams.get('q') || '')
  const [debouncedSearch, setDebouncedSearch] = useState(searchTerm)
  const [wallpapers, setWallpapers] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedCategory, setSelectedCategory] = useState<string>('all')
  const [sortBy, setSortBy] = useState<string>('newest')
  
  // AbortController ref for cancelling in-flight requests
  const abortControllerRef = useRef<AbortController | null>(null)
  
  // Pagination state
  const [currentPage, setCurrentPage] = useState(parseInt(searchParams.get('page') || '1'))
  const [totalPages, setTotalPages] = useState(1)
  const wallpapersPerPage = 24

  // Debounce search input (300ms)
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(searchTerm)
    }, 300)
    
    return () => clearTimeout(timer)
  }, [searchTerm])

  // Sync search and page to URL parameters
  useEffect(() => {
    const params = new URLSearchParams()
    if (debouncedSearch) params.set('q', debouncedSearch)
    if (currentPage > 1) params.set('page', currentPage.toString())
    if (selectedCategory !== 'all') params.set('category', selectedCategory)
    
    setSearchParams(params, { replace: true })
  }, [debouncedSearch, currentPage, selectedCategory, setSearchParams])

  useEffect(() => {
    loadAIWallpapers()
  }, [selectedCategory, sortBy, debouncedSearch, currentPage])

  const loadAIWallpapers = async () => {
    // Cancel previous request if still pending
    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
    }
    
    // Create new abort controller
    const abortController = new AbortController()
    abortControllerRef.current = abortController
    
    setLoading(true)
    try {
      const BASE_URL = import.meta.env.VITE_SUPABASE_URL
      const AUTH_HEADER = `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`
      
      const response = await fetch(
        `${BASE_URL}/functions/v1/wallpapers-api`,
        {
          method: 'POST',
          headers: {
            'Authorization': AUTH_HEADER,
            'Content-Type': 'application/json',
            'apikey': import.meta.env.VITE_SUPABASE_ANON_KEY
          },
          body: JSON.stringify({
            category: selectedCategory === 'all' ? undefined : selectedCategory,
            is_ai: true,
            sort: sortBy,
            limit: wallpapersPerPage,
            page: currentPage,
            search: debouncedSearch || undefined
          }),
          signal: abortController.signal
        }
      )
      
      // Check if request was aborted
      if (abortController.signal.aborted) {
        return
      }

      if (response.ok) {
        const result = await response.json()
        setWallpapers(result.data?.wallpapers || [])
        setTotalPages(result.data?.totalPages || 1)
      } else {
        console.error('Failed to load AI wallpapers:', response.status, response.statusText)
        setWallpapers([])
      }
    } catch (error) {
      // Ignore abort errors
      if (error.name === 'AbortError') {
        return
      }
      console.error('Error loading AI wallpapers:', error)
      setWallpapers([])
      setTotalPages(1)
    } finally {
      // Only clear loading if this is still the current request
      if (!abortController.signal.aborted) {
        setLoading(false)
      }
    }
  }

  // Page change handler
  const handlePageChange = (page: number) => {
    setCurrentPage(page)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  // Category/Sort change handler (reset page and toggle)
  const handleCategoryChange = (category: string) => {
    setSelectedCategory(selectedCategory === category ? 'all' : category)
    setCurrentPage(1)
  }

  const handleSortChange = (sort: string) => {
    setSortBy(sort)
    setCurrentPage(1)
  }
  
  // Clear all filters handler
  const handleClearFilters = () => {
    setSearchTerm('')
    setSelectedCategory('all')
    setSortBy('newest')
    setCurrentPage(1)
  }

  // SEO Configuration for AI Wallpapers Page
  const seoConfig = {
    title: 'AI Generated Wallpapers - Stunning AI Art Backgrounds 2025',
    description: 'Discover unique AI-generated wallpapers created by advanced artificial intelligence. Download stunning AI art backgrounds in 4K quality. New AI wallpapers added daily.',
    keywords: [
      'ai wallpapers',
      'ai generated wallpapers',
      'artificial intelligence wallpapers',
      'ai art wallpapers',
      'machine learning wallpapers',
      'stable diffusion wallpapers',
      'dall-e wallpapers',
      'ai backgrounds',
      'ai desktop wallpapers',
      'neural network art',
      'generative art wallpapers',
      'ai mobile wallpapers'
    ],
    image: '/images/og-ai-wallpapers.jpg',
    type: 'website' as const
  }

  const breadcrumbs = [
    { name: 'Home', url: '/' },
    { name: 'AI Wallpapers', url: '/ai-wallpapers' }
  ]

  const structuredData = [
    generateBreadcrumbSchema(breadcrumbs),
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      "name": "AI Generated Wallpapers",
      "description": "Unique wallpapers created by artificial intelligence",
      "url": "https://efioh8fr8no7.space.minimax.io/ai-wallpapers",
      "mainEntity": {
        "@type": "ImageGallery",
        "name": "AI Wallpapers Collection",
        "description": "AI-generated art and wallpapers",
        "numberOfItems": wallpapers.length
      }
    },
    ...wallpapers.slice(0, 6).map(wallpaper => generateImageObjectSchema(wallpaper))
  ]

  return (
    <div className={`min-h-screen ${theme === 'dark' ? 'bg-dark-primary text-white' : 'bg-gray-50 text-gray-900'} transition-colors duration-200`}>
      <SEOHead config={seoConfig} structuredData={structuredData} />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-700 text-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex justify-center mb-6">
              <div className="w-20 h-20 bg-gradient-to-r from-violet-400 to-purple-400 rounded-2xl flex items-center justify-center">
                <Wand2 className="w-10 h-10 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 leading-tight">
              AI Generated Wallpapers
            </h1>
            <p className="text-xl md:text-2xl mb-8 text-purple-100 max-w-4xl mx-auto leading-relaxed">
              Discover unique wallpapers created by cutting-edge artificial intelligence. Experience the future of digital art with our AI-generated backgrounds.
            </p>
            
            {/* Stats */}
            <div className="grid grid-cols-3 gap-4 max-w-md mx-auto mb-8">
              <div className="text-center">
                <div className="text-3xl font-bold">1K+</div>
                <div className="text-sm opacity-90">AI Wallpapers</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold">100%</div>
                <div className="text-sm opacity-90">Unique</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold">4K</div>
                <div className="text-sm opacity-90">Quality</div>
              </div>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center max-w-md mx-auto">
              <button 
                onClick={() => document.getElementById('ai-gallery')?.scrollIntoView({ behavior: 'smooth' })}
                className="bg-white text-violet-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition duration-200 inline-flex items-center justify-center"
              >
                <Download className="w-5 h-5 mr-2" />
                Explore Collection
              </button>
              <Link
                to="/mobile-wallpapers"
                className="bg-transparent border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-violet-600 transition duration-200 inline-flex items-center justify-center"
              >
                <Sparkles className="w-5 h-5 mr-2" />
                Mobile AI
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* AI Features */}
      <section className={`py-16 ${theme === 'dark' ? 'bg-dark-secondary' : 'bg-white'} transition-colors duration-200`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className={`text-3xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'} mb-4`}>
              Powered by Advanced AI
            </h2>
            <p className={`text-lg ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'} max-w-2xl mx-auto`}>
              Our AI wallpapers are created using the latest machine learning models and neural networks
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {aiFeatures.map((feature, index) => (
              <div
                key={index}
                className={`p-6 rounded-xl text-center ${theme === 'dark' ? 'bg-dark-tertiary border border-dark-border' : 'bg-gray-50 border border-gray-200'} hover:shadow-lg transition-all duration-200`}
              >
                <div className="w-12 h-12 bg-gradient-to-r from-violet-500 to-purple-500 rounded-lg flex items-center justify-center text-white mx-auto mb-4">
                  {feature.icon}
                </div>
                <h3 className={`text-lg font-semibold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
                  {feature.title}
                </h3>
                <p className={`text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-600'}`}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* AI Categories */}
      <section className={`py-16 ${theme === 'dark' ? 'bg-dark-primary' : 'bg-gray-50'} transition-colors duration-200`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className={`text-3xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'} mb-4`}>
              AI Wallpaper Categories
            </h2>
            <p className={`text-lg ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'} max-w-2xl mx-auto`}>
              Explore different styles of AI-generated wallpapers
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {aiCategories.map((category, index) => (
              <button
                key={category.slug}
                onClick={() => handleCategoryChange(category.slug)}
                className={`p-6 rounded-xl text-left transition-all duration-200 hover:scale-105 ${
                  selectedCategory === category.slug
                    ? 'bg-gradient-to-r from-violet-500 to-purple-500 text-white'
                    : theme === 'dark'
                    ? 'bg-dark-secondary border border-dark-border hover:border-violet-500'
                    : 'bg-white border border-gray-200 hover:border-violet-400 hover:shadow-lg'
                }`}
              >
                <div className="flex items-center mb-4">
                  <span className="text-3xl mr-4">{category.icon}</span>
                  <div>
                    <h3 className={`text-xl font-semibold ${
                      selectedCategory === category.slug
                        ? 'text-white'
                        : theme === 'dark' ? 'text-white' : 'text-gray-900'
                    }`}>
                      {category.name}
                    </h3>
                  </div>
                </div>
                <p className={`text-sm ${
                  selectedCategory === category.slug
                    ? 'text-purple-100'
                    : theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
                }`}>
                  {category.description}
                </p>
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Controls and Gallery */}
      <section id="ai-gallery" className={`py-8 ${theme === 'dark' ? 'bg-dark-secondary border-dark-border' : 'bg-white border-gray-200'} border-t transition-colors duration-200`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Sort Controls */}
          <div className="flex flex-col sm:flex-row gap-4 items-center justify-between mb-8">
            <h3 className={`text-2xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
              {selectedCategory === 'all' ? 'All AI Wallpapers' : aiCategories.find(c => c.slug === selectedCategory)?.name}
            </h3>
            
            {/* Search Input */}
            <div className="relative flex-1 max-w-md">
              <Search className={`absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 ${theme === 'dark' ? 'text-gray-400' : 'text-gray-400'}`} />
              <input
                type="text"
                placeholder="Search AI wallpapers..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className={`pl-10 pr-4 py-3 w-full rounded-lg border ${
                  theme === 'dark' 
                    ? 'bg-dark-secondary border-dark-border text-white placeholder-gray-400' 
                    : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'
                } focus:ring-2 focus:ring-violet-500 focus:border-transparent transition-colors duration-200`}
              />
            </div>
            
            {/* Clear Filters Button */}
            {(searchTerm || selectedCategory !== 'all') && (
              <button
                onClick={handleClearFilters}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200 inline-flex items-center ${
                  theme === 'dark'
                    ? 'bg-dark-secondary text-gray-300 hover:bg-dark-tertiary border border-dark-border'
                    : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'
                }`}
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                Clear Filters
              </button>
            )}
            
            <div className="flex gap-2">
              <select
                value={sortBy}
                onChange={(e) => handleSortChange(e.target.value)}
                className={`px-4 py-2 rounded-lg border ${theme === 'dark' ? 'bg-dark-tertiary border-dark-border text-white' : 'bg-white border-gray-300 text-gray-900'} focus:ring-2 focus:ring-violet-500 focus:border-transparent`}
              >
                <option value="newest">Newest First</option>
                <option value="popular">Most Popular</option>
                <option value="trending">Trending</option>
              </select>
            </div>
          </div>
          
          {/* Gallery */}
          {loading ? (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4">
              {Array.from({ length: 24 }).map((_, index) => (
                <div
                  key={index}
                  className={`aspect-[9/16] rounded-lg ${theme === 'dark' ? 'bg-dark-tertiary' : 'bg-gray-200'} animate-pulse`}
                />
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4">
              {wallpapers.map((wallpaper, index) => (
                <EnhancedWallpaperCardAdapter
                  key={wallpaper.id}
                  wallpaper={wallpaper}
                  className="aspect-[9/16]"
                  priority={index < 10}
                  variant="compact"
                />
              ))}
            </div>
          )}
          
          {!loading && wallpapers.length === 0 && (
            <div className="text-center py-12">
              <Sparkles className={`w-16 h-16 mx-auto mb-4 ${theme === 'dark' ? 'text-gray-400' : 'text-gray-400'}`} />
              <h3 className={`text-xl font-semibold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
                AI wallpapers coming soon
              </h3>
              <p className={`${theme === 'dark' ? 'text-gray-400' : 'text-gray-600'}`}>
                Our AI is working hard to generate new wallpapers for this category
              </p>
            </div>
          )}
          
          {/* Pagination Controls */}
          {totalPages > 1 && !loading && (
            <div className="mt-12 flex justify-center">
              <div className="flex items-center space-x-2">
                <button
                  onClick={() => handlePageChange(currentPage - 1)}
                  disabled={currentPage === 1}
                  className={`px-4 py-2 border rounded-lg transition-colors duration-200 ${
                    theme === 'dark'
                      ? 'border-dark-border text-white hover:bg-dark-secondary disabled:opacity-50 disabled:cursor-not-allowed'
                      : 'border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed'
                  }`}
                >
                  <span className="hidden sm:inline">Previous</span>
                  <span className="sm:hidden">Prev</span>
                </button>
                
                {[...Array(Math.min(5, totalPages))].map((_, i) => {
                  const page = Math.max(1, currentPage - 2) + i
                  if (page > totalPages) return null
                  
                  return (
                    <button
                      key={page}
                      onClick={() => handlePageChange(page)}
                      className={`px-4 py-2 rounded-lg transition-colors duration-200 ${
                        currentPage === page
                          ? 'bg-violet-600 text-white'
                          : theme === 'dark'
                          ? 'border border-dark-border text-white hover:bg-dark-secondary'
                          : 'border border-gray-300 text-gray-700 hover:bg-gray-50'
                      }`}
                    >
                      {page}
                    </button>
                  )
                })}
                
                <button
                  onClick={() => handlePageChange(currentPage + 1)}
                  disabled={currentPage === totalPages}
                  className={`px-4 py-2 border rounded-lg transition-colors duration-200 ${
                    theme === 'dark'
                      ? 'border-dark-border text-white hover:bg-dark-secondary disabled:opacity-50 disabled:cursor-not-allowed'
                      : 'border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed'
                  }`}
                >
                  <span className="hidden sm:inline">Next</span>
                  <span className="sm:hidden">Next</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* CTA Section */}
      <section className={`py-16 ${theme === 'dark' ? 'bg-dark-primary' : 'bg-gray-50'} transition-colors duration-200`}>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className={`text-3xl font-bold ${theme === 'dark' ? 'text-white' : 'text-gray-900'} mb-6`}>
            Experience the Future of Digital Art
          </h2>
          <p className={`text-lg ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'} mb-8 max-w-2xl mx-auto`}>
            Join the AI revolution in wallpaper design. Discover unique, never-before-seen artwork created by artificial intelligence.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/mobile-wallpapers"
              className="bg-violet-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-violet-700 transition duration-200 inline-flex items-center justify-center"
            >
              <Sparkles className="w-5 h-5 mr-2" />
              Mobile AI Wallpapers
            </Link>
            <Link
              to="/premium"
              className={`border-2 border-violet-600 text-violet-600 px-8 py-3 rounded-lg font-semibold hover:bg-violet-600 hover:text-white transition duration-200 inline-flex items-center justify-center`}
            >
              <Star className="w-5 h-5 mr-2" />
              Premium AI Collection
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}