-- Performance optimization indexes for wallpapers and related tables
-- This migration adds indexes to improve query performance for common operations

-- Wallpapers table indexes for common queries
CREATE INDEX IF NOT EXISTS idx_wallpapers_published_active 
ON public.wallpapers(is_published, is_active, created_at DESC) 
WHERE is_published = true AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_wallpapers_category_published 
ON public.wallpapers(category_id, is_published, is_active, created_at DESC) 
WHERE is_published = true AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_wallpapers_premium_published 
ON public.wallpapers(is_premium, is_published, is_active, created_at DESC) 
WHERE is_published = true AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_wallpapers_download_count 
ON public.wallpapers(download_count DESC, created_at DESC) 
WHERE is_published = true AND is_active = true;

-- Full-text search index for wallpapers
CREATE INDEX IF NOT EXISTS idx_wallpapers_search 
ON public.wallpapers USING GIN (to_tsvector('english', title || ' ' || COALESCE(description, ''))) 
WHERE is_published = true AND is_active = true;

-- Slug indexes for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_wallpapers_slug_unique 
ON public.wallpapers(slug) 
WHERE is_published = true AND is_active = true;

CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_slug_unique 
ON public.categories(slug) 
WHERE is_active = true;

CREATE UNIQUE INDEX IF NOT EXISTS idx_collections_slug_unique 
ON public.collections(slug) 
WHERE is_active = true;

-- Collection wallpapers indexes
CREATE INDEX IF NOT EXISTS idx_collection_wallpapers_collection_sort 
ON public.collection_wallpapers(collection_id, sort_order ASC);

CREATE INDEX IF NOT EXISTS idx_collection_wallpapers_wallpaper 
ON public.collection_wallpapers(wallpaper_id);

-- Categories optimization
CREATE INDEX IF NOT EXISTS idx_categories_active_sort 
ON public.categories(is_active, sort_order ASC) 
WHERE is_active = true;

-- Collections optimization
CREATE INDEX IF NOT EXISTS idx_collections_active_featured 
ON public.collections(is_active, is_featured, sort_order ASC) 
WHERE is_active = true;

-- Performance monitoring table for tracking slow queries
CREATE TABLE IF NOT EXISTS public.performance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  query_type TEXT NOT NULL,
  execution_time_ms INTEGER NOT NULL,
  parameters JSONB,
  user_agent TEXT,
  ip_address TEXT
);

-- Index for performance logs
CREATE INDEX IF NOT EXISTS idx_performance_logs_query_time 
ON public.performance_logs(query_type, created_at DESC, execution_time_ms DESC);

-- Enable RLS on performance logs
ALTER TABLE public.performance_logs ENABLE ROW LEVEL SECURITY;

-- Policy for performance logs (admin access only)
CREATE POLICY "Allow authenticated users to insert performance logs" 
ON public.performance_logs FOR INSERT 
USING (auth.role() = 'authenticated');

CREATE POLICY "Allow admin to read performance logs" 
ON public.performance_logs FOR SELECT 
USING (auth.role() = 'authenticated');

-- Add comments for documentation
COMMENT ON TABLE public.performance_logs IS 'Logs for monitoring query performance and optimization';
COMMENT ON INDEX idx_wallpapers_published_active IS 'Optimizes queries for published and active wallpapers';
COMMENT ON INDEX idx_wallpapers_search IS 'Full-text search index for wallpaper titles and descriptions';
